# orchestrator/orchestrator_mcp.py
import asyncio
from orchestrator.mcp_client import call_mcp_tool
from orchestrator.state import WorkflowState

# MCP Server URLs
GITHUB_MCP = "http://127.0.0.1:8010"
JENKINS_MCP = "http://127.0.0.1:8020"

state = WorkflowState()

async def phase_0_trigger():
    print("🚀 Phase 0: Trigger received.")
    state.repo = "octocat/Hello-World"
    state.branch = "main"
    state.commit_sha = "mock-sha"
    state.phase = "trigger"
    print(f"→ Repository: {state.repo}")
    state.save()

async def phase_1_regression_validation():
    print("\n🧪 Phase 1: Running regression tests...")
    # Simulate Jenkins test trigger
    res = await call_mcp_tool(JENKINS_MCP, "tools/call", "trigger_job", {"name": "run-tests"})
    print(f"Triggered test run → {res}")
    state.phase = "regression_validation"
    state.save()

async def phase_2_failure_diagnosis():
    print("\n🔍 Phase 2: Diagnosing failing tests...")
    # Example: Fetch diff of changed code
    res = await call_mcp_tool(GITHUB_MCP, "tools/call", "get_commit_diff", {
        "owner": "octocat",
        "repo": "Hello-World",
        "base": "main",
        "head": "feature-branch"
    })
    print(f"Changed files → {len(res['result']['changed_files'])}")
    state.failed_tests = ["test_login_flow", "test_signup"]
    state.phase = "failure_diagnosis"
    state.save()

async def phase_3_test_generation():
    print("\n🧩 Phase 3: Generating and fixing tests...")
    for test in state.failed_tests:
        fix = {
            "test_name": test,
            "patch": f"Mock patch for {test}",
            "rationale": "Autogenerated by MCP LLM layer"
        }
        state.proposed_fixes.append(fix)
        print(f"Proposed fix → {fix['test_name']}")
    state.phase = "test_generation"
    state.save()

async def phase_4_user_approval():
    print("\n🧠 Phase 4: Waiting for user approval...")
    res = await call_mcp_tool(GITHUB_MCP, "tools/call", "post_pr_comment", {
        "owner": "octocat",
        "repo": "Hello-World",
        "pr_number": 1,
        "body": "Proposed test fixes available for review."
    })
    print(f"Posted comment: {res['result']}")
    state.phase = "user_approval"
    state.save()

async def phase_5_patch_and_retest():
    print("\n♻️ Phase 5: Applying patches and re-testing...")
    res = await call_mcp_tool(JENKINS_MCP, "tools/call", "trigger_job", {"name": "retest-approved"})
    print(f"Triggered re-test → {res}")
    state.phase = "patch_and_retest"
    state.save()

async def run_workflow():
    await phase_0_trigger()
    await phase_1_regression_validation()
    await phase_2_failure_diagnosis()
    await phase_3_test_generation()
    await phase_4_user_approval()
    await phase_5_patch_and_retest()
    print("\n✅ Workflow complete.")
    print(state.summary())

if __name__ == "__main__":
    asyncio.run(run_workflow())
